### ISSUE TITLE
[Enhancement] Get (public) samples in timerange

### ISSUE THREAD

**Issue by JScharloo** [hatching/triage#2]
To avoid querying your API too much, I would like to retrieve public and possibly private samples by specifying a timerange.

Currently I can select a maximum number. Ideally I would like to retrieve all samples (and then reports) from the last X time (e.g. last 24 hours).

**Comment by JScharloo** [comment]
Also, a filter would be handy. Specifically for the status. (Running, Reported, etc)

**Comment by sisoma2** [comment]
I agree with the request! I would like the smae for the search API endpoint

**Comment by jbremer** [comment]
Thanks for the request above! This has been implemented since a few weeks BTW. E.g., https://tria.ge/s?q=family%3Adridex+from%3A2021-04-10+to%3A2021-04-12 :-)
Let me know if there are additional requests or if this ticket can be closed.
