### ISSUE TITLE
Update requests package version

### ISSUE THREAD

**Issue by m4rb3n** [hatching/triage#20]
As this use a strict requests version (2.25.1) it causes some dependencies issues when trying to install alongside other packages.
An example is when installing alongside the latest version of pymisp (2.4.159).

**Comment by RicoVZ** [comment]
Hey @m4rb3n,

Thanks for reporting this. Should be fixed now. See: https://github.com/hatching/triage/pull/21.

We have not yet deployed a new Pypi package.
