### ISSUE TITLE
When fetching report by ID the CLI shouldn't require 'sample' argument

### ISSUE THREAD

**Issue by tlansec** [hatching/triage#4]
TLDR, the following should be possible:

```
λ triage report --task 210927-l2xqfanyk1
Usage: triage report [OPTIONS] SAMPLE
Try 'triage report --help' for help.

Error: Missing argument 'SAMPLE'.
```

If I know the ID of the report, I shouldn't require the sample aswell.

Cheers,
Tom

**Comment by jbremer** [comment]
Hi @tlansec, sorry for delay in replying. Did you also try `triage report 210927-l2xqfanyk1`?

**Comment by tlansec** [comment]
Hey,

I am aware that option is possible. 

I think this boils down to the fact that as a new user i had:

* initially expected that 'sample' would be a hash of a file, not an ID assigned from your sandbox. 
* in the absence of this, I had expected that the task would be the ID of the sandbox run and that would be sufficient on its own to ID an analysis to return results to me.

Cheers,
Tom

**Comment by RicoVZ** [comment]
Hi @tlansec,

I understand those expectations with that terminology. In our platform a 'sample/sample id' refers to the unique ID each submitted sample/url gets. The task/task id refers to the type of task with a counter behind it. So behavioral1, behavioral2, static1, etc. All of these tasks are part of the same submission.

So, (as you probably already discovered), an example use of the `triage report` command to retrieve `behavioral1` of sample `221109-ttn3bsacb8` would be:

```
$ triage report 221109-ttn3bsacb8 --task behavioral1
```
Output example:

```
~behavioral1 Report~
putty.exe
  md5: b6c12d88eeb910784d75a5e4df954001
  score: 1
  tags: []
```

The same command, but without specifying the task id:

```
$ triage report 221109-ttn3bsacb8
```
Output:
```
~Overview~
putty.exe
  md5: b6c12d88eeb910784d75a5e4df954001
  score: 1
  family: None
  tags: []

  behavioral1
    score: 1
    platform: windows7-x64
    tags: []
  behavioral2
    score: 1
    platform: windows10-2004-x64
    tags: []
  static1
    score: N/A
    tags: []
```

I hope this helps.

I'm closing the issue. Feel free to open it again if you have additional questions.
